### ISSUE TITLE
Playlist referencing other playlists wont update over 145 tracks

### ISSUE THREAD

**Issue by ephoras** [simon-weber/Autoplaylists-for-Google-Music#149] opened 2017-04-25 21:11 UTC
i just created a playlist to test the extension and no matter what i do, the Playlist always tops out at 145 tracks.
Is this some limitation? Or what can i check?

**Comment by simon-weber** [comment] 2017-04-25 21:19
Huh. Nope, there shouldn't be any limits on playlist size besides Google's 1k limit.

My bet would be that the playlists you're linking contains subscription tracks that haven't been added to your library. Can you check if that matches with which tracks you see and don't see in the test result? I think non-library tracks will have a prompt like "add to library" when right-clicked in Google's ui that you can use to verify their type.

**Comment by ephoras** [comment] 2017-04-26 10:39
Ai, thanks...
That fixed it. Had to go through all my playlists and add them to my music. Bad news is, one can only add a few tracks at once (no real number here, some times it worked if i highlighted 10 tracks, sometimes it worked with 30+)
Now my auto playlist works like a charm ;)

**Comment by simon-weber** [comment] 2017-04-26 15:18
Sorry for the trouble, but glad that fixed it!

I'll close this as a dupe of https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119. It's the next big thing I'm planning to work on (though I've been super busy lately, so I'm not sure when I'll find the time).

**Closed by simon-weber** 2017-04-26 15:18 UTC
Labels: bug
