### ISSUE TITLE
Playlist count not syncing properly

### ISSUE THREAD

**Issue by Adith3ya** [simon-weber/Autoplaylists-for-Google-Music#117] opened 2016-12-13 21:42 UTC
Hi

I started using the Autoplaylist extension. First up, kudos for that. It is amazing. Secondly, I found a problem with the playlist generation. I am not sure if this has already been addressed but I tried to generate an auto playlist. I have a playlist on Google Play music with about 970 odd songs (Name: Favorites - Overall 1). I generated a playlist where the playlist is equal to Favorites - Overall 1. The generated playlist did not have the same count as the actual one. 

I have attached the screenshots for all that. Do let me know what the problem is. 

![1](https://cloud.githubusercontent.com/assets/24554704/21160494/ed2e17c6-c139-11e6-91af-1dab98a01821.PNG)
![2](https://cloud.githubusercontent.com/assets/24554704/21160493/ed2ea222-c139-11e6-8d4a-939b3bffaf04.PNG)
![3](https://cloud.githubusercontent.com/assets/24554704/21160495/ed377212-c139-11e6-8d43-340e2ef77bdd.PNG)

**Comment by simon-weber** [comment] 2016-12-13 22:01
Hm. Is it possible that your static playlist "favorites - overall" has duplicate songs? It's not documented anywhere, but autoplaylists currently will only include one copy of a track due to how the local database works.

**Comment by Adith3ya** [comment] 2016-12-13 22:10
I checked for it. I initially had 1000 songs. I manually vetted them all and removed duplicates and brought it down to 979. I know for sure that 144 duplicates is not possible at all. 

Also, I did notice this. Most of the songs that were missing were AA. I tried searching for specific AA songs from Favorites - Overall - 1 under Test.

**Comment by simon-weber** [comment] 2016-12-13 22:18
Gotcha; thanks for checking. In that case we'll have to look for more general syncing issues. Here's what I'd recommend:
* try [reloading the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension), then making a small change to the autoplaylist (like the name) to force a sync: if the playlist cache is out of sync, this should fix it
* if that doesn't work, [check the logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) for warnings or errors
* if nothing stands out in the logs, go to settings, disable "enable new sync api", then reload the extension and force another sync: it's possible there's something weird going on with new syncing and AA tracks, though it's worked fine in my testing

Hopefully one of these will get things working again!

**Comment by Adith3ya** [comment] 2016-12-13 22:34
Alright. I tried reloading the extension but it did not work.

I then looked at the log. There were a couple of errors. Those were actually repetitions of this error: 
![1](https://cloud.githubusercontent.com/assets/24554704/21162226/3174d6b6-c141-11e6-8e08-143595f13294.PNG)

Do let me know.

**Comment by simon-weber** [comment] 2016-12-13 22:52
Huh. GA is used for anonymous metrics (like tracking successful vs failed syncs) and shouldn't have much to do with syncing. I've never run into it locally, though, so it's possible there's something I need to do to handle the error.

Can you try filtering the logs for "combined entry res", then expanding a few of them and checking the length of the mutate_response? Here's an example from my logs:
![image](https://cloud.githubusercontent.com/assets/950506/21162696/bfbffb4c-c15c-11e6-9763-f93a49b765a4.png)

If they're all similar lengths, it might mean we're trying to sync the same tracks over and over. It's also worth expanding the array and spot checking a few of the entries: Google will occasionally send back more details on errors there (which I need to do a better job of logging).

**Comment by Adith3ya** [comment] 2016-12-13 23:22
Attaching the screenshot of the filtered log. Do help me out.

Also, do let me know if you need additional information.

![1](https://cloud.githubusercontent.com/assets/24554704/21163009/4c4be408-c145-11e6-84db-b76a2774f8ef.PNG)

**Comment by Adith3ya** [comment] 2016-12-13 23:31
I also checked the objects of the array. Each object had a specific id and for the objects and the response code was "Ok".

**Comment by simon-weber** [comment] 2016-12-13 23:40
Hm. If you let the preiodic syncs happen for a bit, does the number of tracks on Google's end increase over time? The slow decrease in mutations seems to suggest that (though it could also mean the ordering is becoming more correct).

**Comment by Adith3ya** [comment] 2016-12-13 23:44
The total number of tracks is still at 835. There are AA songs in the playlist too. Also, I can also see that the songs that are missing are also AA ones. Could it be because of some kind of error with the id may be?

**Comment by simon-weber** [comment] 2016-12-13 23:51
Possibly. I've had strange problems with AA tracks in the past.

If you compared a working AA track vs a nonworking one, do they have the same type? The easiest way to make it show up in the results is to sort on it (you can also use the [debugging interface](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#manually-making-queries) and a query like `Track.id.eq('...')`). One possibility is that the working tracks are added to your library while the nonworking tracks are not (they're only added to the playlist), though I think that would have different symptoms.

**Comment by Adith3ya** [comment] 2016-12-26 02:26
I have bee trying to figure this out and I think I just did. Google music has been ignoring songs in  these two scenarios:

- I have a huge collection that I uploaded and a lot of those songs are already there on Google music. Rather than deleting the ones I uploaded, I just selected 'Use Suggestions' to link the uploaded song with that of the ones which are AA, such that I will hear the uploaded rather than the one provided by Google Play subscription
- If the song you added on your playlist is not available on your library as well

Is there any short fix for this? God I am going through my playlist vetting it one at a time.

**Comment by simon-weber** [comment] 2016-12-29 20:57
Hey there! Sorry for the delay; I'm just now digging myself out from under a pile of holiday emails.

> If the song you added on your playlist is not available on your library as well

Ah, yes, this is what I was thinking in my previous comment. Right now, the track cache is filled by requesting all the songs in your library, so these ones never end up getting pulled in. Google seems to treat them as normal AA tracks otherwise (type 5 + a store id in the web interface), so fixing this boils down to finding a way to get their extended metadata. I'm tracking this separately in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119, but I'm not confident Google's apis will easily support a fix.

> Rather than deleting the ones I uploaded, I just selected 'Use Suggestions' to link the uploaded song 

Are you able to find these tracks in your library? These sound like normal scan-and-match tracks, which I'd expect to work just fine.

> Is there any short fix for this?

The only thing I can think of in the short term is making sure all songs in linked playlists have been added to your library. https://productforums.google.com/forum/#!topic/play/CDzcG3Y3PUk describes a way to do this per-playlist.

**Comment by simon-weber** [comment] 2017-03-19 16:26
I'm going to close this as a duplicate of https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119; feel free to add a comment if that's not right.

**Closed by simon-weber** 2017-03-19 16:26 UTC
