### ISSUE TITLE
Combining All and Any

### ISSUE THREAD

**Issue by Yinka** [simon-weber/Autoplaylists-for-Google-Music#63] opened 2016-04-24 00:43 UTC
What is the best way to combine `any` and `all` in this sense:

```
All :
 - Play count greater than 1
 - Thumbs up isn't down

Any:
 - Genre = Classic rock
 - Genre = Hard rock
 - Genre = Folk

Sort:
 - Play count
```

What I want is first combine Classic Rock, Hard Rock and Folk genres and then return result where playcount is >1 and thumb-up <> down.

Thanks.

**Comment by simon-weber** [comment] 2016-04-24 00:44
I think you just need an extra layer of nesting:
* all
  * any
    * genre...
    * genre...
  * play count...
  * thumbs...

**Comment by Yinka** [comment] 2016-04-24 01:16
Thanks, will try that.

**Comment by Yinka** [comment] 2016-04-24 22:48
works

**Comment by Yinka** [comment] 2016-08-14 22:27
Just a quick question please

I have a playlist `ClassicRock`

```
All
    Any
         genre = Classic Rock
         genre = Post Punk
    Playcount >1
    Rating not down
```

I need another one for `Modern Rock` that contains `Rock` but exlcudes the above playlist, so I did:

```

    All
         genre contains Rock
         genre not contains Afro
         Playlist not equal Classic Rock
```

This still returns songs from playlist `Classic Rock`, any advise?

Thank you

**Comment by simon-weber** [comment] 2016-08-14 23:05
Hm, that looks like it should do what you expect. I did a test just now with a similar set of playlists and didn't notice anything out of place.

**Comment by Yinka** [comment] 2016-08-14 23:23
I thought the query look okay too.

Pasted it below just so you see it better

I'll use a workaround for now.
 

> **Playlist 1**

![image](https://cloud.githubusercontent.com/assets/87303/17652756/675726d0-627d-11e6-851b-cba27055fcdb.png)

> **Playlist 2**

![image](https://cloud.githubusercontent.com/assets/87303/17652760/8fed90ca-627d-11e6-9c2d-fd07b20fb83c.png)

> **Result of Playlist 2**

![image](https://cloud.githubusercontent.com/assets/87303/17652770/bb9c603e-627d-11e6-8600-f4d5bf99cac7.png)

**Comment by simon-weber** [comment] 2016-08-14 23:39
Bizarre. A few shots in the dark:
* can you double check that these songs are in playlist 1?
* can you try [reloading the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension)? Maybe your cache is out of sync.
* do you notice anything strange [in the logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs)?
* can you find any songs from playlist 1 that _are_ excluded from playlist 2? Is there anything different about them?

**Comment by Yinka** [comment] 2016-08-15 00:09
I think I found it. It was applying the limit/sort of playlist 1

Did you eventually fix the sort/limit issue on playlist linking?

**Comment by simon-weber** [comment] 2016-08-15 14:28
Hm, sorts and limits shouldn't apply at all when linking other autoplaylists (though they do when linking static playlists). I'm not sure why changing that one condition could affect anything.

Any luck with the other debugging ideas?

**Comment by simon-weber** [comment] 2016-11-22 20:58
My guess is this was caused by https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/75, which is fixed now. Feel free to reopen if it's still a problem.

**Closed by simon-weber** 2016-11-22 20:58 UTC
