### ISSUE TITLE
some songs are not included in the playlist, even though they match the criteria

### ISSUE THREAD

**Issue by PeteRepeat77** [simon-weber/Autoplaylists-for-Google-Music#35] opened 2016-02-02 21:42 UTC
I can't see anything related to this so wondering if it's isolated (or I didn't look too well). 

There is a problem, followed by questions. If you'd like me to split these into two topics I can but thought it's best not to when they are questions relating to the same playlist rather than two seperate problems.

I have a playlist that is created by "greater than rating 3" AND "last played before 30 days ago" and sorted by "last played descending". And limited to 1000. I think they are the terms but away from the pc.

Main problem is, the playlist summary says the rules give a total of over 2000 songs and originally the limit meant the playlist was 1000 songs exactly. But since clicking thumbs down on a number of songs they appear to be removed instantly from the playlist and it has reduced to 980 songs but  hasn't repopulated with new songs that match the criteria even though there are plenty of sings that do. I think the reduction is due to thumbs down and not the last played criteria but not certain.

The playlist seems to be updating occasionally (the title of the playlist says that anyway) although I noticed it hadn't updated since yesterday until I went into the playlist and  saved it again. Although this is not my concern at the moment, nor have I looked into what could cause it to not update for the past day. 

First question is, before 30 days ago means more than 30 days ago, as in 30, 31.... 100 days yes? 

Second question is,  last played ascending sorts them into 30 days ago, 31 days ago, 32 days ago....  A long long time ago yes?

**Comment by PeteRepeat77** [comment] 2016-02-02 21:43
This is with the latest store version I believe

**Comment by simon-weber** [comment] 2016-02-02 23:41
Can you paste the description of your playlist? I have a similar playlist which formats as the following:
```
... to contain: (lastPlayed < 30 days ago and playCount > 10) sort by playCount descending.
```

I _think_ mine works as expected and yours is backwards currently. This is a really interesting ux thing that I hadn't put much thought into; do you have ideas on how to make this rule more clear?

#### how this works currently

Behind the scenes, lastPlayed is represented as a timestamp (roughly, seconds since 1970), so larger values are more recent in time:

```
<-- timestamp 0 (1970) ... timestamp 31 million (1971) ... timestamp 1.4 billion (time I'm posting) -->
```

So, "X is before Y" is interpreted as "X has a timestamp smaller than Y".

#### what I think happened
This gets confusing when we're dealing with relative times like "30 days ago". The way this works right now is that the relative datetime is converted to an absolute time, dynamically. Something like:
* find songs played before "30 days ago"
* -> timestamp exactly 30 days ago is January 2nd at ... (for example)
* -> find songs where `lastPlayed < timestamp(January 2nd at ...)`

I think the way you were thinking about it was that the _time differences_ were being compared instead, something like:
* find songs played before "30 days ago"
* -> the difference between now and 30 days ago is 30 days
* -> which songs where `(now - lastPlayed) < (30 days)`

**Comment by PeteRepeat77** [comment] 2016-02-03 04:23
**Problem:**
I have attached two screen shots, well links to dropbox. This shows the problem I am having.

[](https://www.dropbox.com/sh/581pn21tczmlcwp/AAB1K1xld4-4Z_eHMnltag7Za?dl=0)

Notice the song count is less than 1000, even though the rules return over 3000 songs and the limit is set at 1000.

**Questions and answers;**
When I wrote the playlist I interpreted it as you have suggested. But I did think about it, more in a programming perspective as I have used Matlab and VBA a reasonable amount (although definitely no programmer). My last post had less thought... If I think of a clearer way then I'll post back here.

**Comment by PeteRepeat77** [comment] 2016-02-03 04:23
https://www.dropbox.com/sh/581pn21tczmlcwp/AAB1K1xld4-4Z_eHMnltag7Za?dl=0[](url)

**Comment by simon-weber** [comment] 2016-02-03 15:49
Yeah, not sure why it's not syncing up to 1k tracks. Maybe try sending me the logs again? 0.9.2 has better logging for this situation.

**Comment by PeteRepeat77** [comment] 2016-02-03 21:30
Happy this post is removed if you want to keep this topic tidy. 

I'll grab the logs.

I'd prefer not to remove the store version (which I assume 0.9.2 isn't) as I lose the playlist file don't I? Well I did before when I had to keep removing the extension when it was disabled by chrome. I think a drag and drop installs another copy of the extension rather than an upgrade? 

Are the playlist files stored locally on each pc that I have the extension installed on? So I can just copy it back to the new install?

**Comment by simon-weber** [comment] 2016-02-03 21:50
Shouldn't be a problem: 0.9.2 is the latest store version. You can check your version on chrome://extensions.

**Comment by PeteRepeat77** [comment] 2016-02-03 23:17
Thanks. I realised I had 0.9.2 once I got to the PC.

Link above now has log files.

I have saved the console messages at text files. Is this the best way?

I have attached two logs. one that was cleared just before I re-save the playlist. The other with lots more in it.

**Comment by simon-weber** [comment] 2016-02-04 22:05
I think this is caused by the same thing as https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/20, actually. Looking at your logs shows the same "0, 2, 0" failure response when attempting to add these tracks.

That's probably a good thing, since if the hypothesis of a weird song causing this problem is true, we've narrowed it down to < 200 songs.

This is kind of a weird request, but can you search the number of tracks until you find the first one causing a problem? eg set your limit to 900 -- if it fails to sync, we know the bad track is in tracks 800-900. Then try a limit of 850, etc. Eventually, you should find that it syncs successfully at limit X, while failing to sync at X+1.

Then, we can pull the track id from either the "add response" line in the logs (it should be the last one in the list) or the request from the network tab. Finally, to get its full information, we can make a playlist with "id equals <track id>" and test it.

**Comment by PeteRepeat77** [comment] 2016-02-07 10:01
Looks like I can only add one playlist with the free version so probably won't delete my playlist just yet to make room for the playlist with the title equals statement. Hoping that the following code helps. It errors out at 803 tracks, and this is the 804 song which pops up in the log as well so feel this is the problem. 

Is this enough info or should I delete my other playlist and create one just for this track? I can't see the pay option to add more playlists. 

not a 0-track add; retrying syncPlaylist [Array[3], Array[2]]
index for 03334274646832387952 0
syncPlaylist, attempt 3
lock Thumbs Up (not heard in last month)
Thumbs Up (not heard in last month) found 804
first is Object {id: "57930658-aa1f-3295-ae09-b0881e68bfe6", title: "Danger (The Bomb) (12` Mix)", artist: "Ministry of Sound (CD Series)", album: "Clubbers Guide To 2006, Cd 1:", albumArtist: ""â€¦}
playlist a1dcf89b-aebd-4607-8dd3-fed26e4628f6 has 803 entries. first 3: [
  [
    "Trkxbjindb2fhmyfc4rde5wyjde",
    "Hearts (feat. Ev Jones)",
    "https://lh5.ggpht.com/fDWuAFxm8ONgsc3io8XVk9-oz7G2qIflY-fWn9GYoj58mLlwiTbqxGHnZhZ-60L8wg3_KTbxlbY",
    "Thundamentals",
    "So We Can Remember",
    "Thundamentals",

**Comment by simon-weber** [comment] 2016-02-07 13:23
Oof, that was a mistake on my end. You should get an update shortly that lets you enable the full version again: https://groups.google.com/d/msg/autoplaylists-for-google-music/hJ8j5eao4HE/pMYeJtj1DQAJ.

**Comment by simon-weber** [comment] 2016-02-07 13:38
> Is this enough info or should I delete my other playlist and create one just for this track?

The messages there are a bit misleading -- they're the first entry we expect to have in the playlist, and the first entry we find in the playlist, respectively. What we're looking for is the first track we're currently trying to add to the playlist. There's a chance this happens to be the first track you posted, but let's check for sure.

We should be able to find it right now from some of the other log messages. Try to paste both the "adding 1 tracks. first 5 are [..." and "add response [..." multiline messages. I'd expect both to be repeated a bunch of times as we retry to add the track. Note that the first messages needs to be "adding _1_ track" so we know this is the exact one (which I believe should happen when your limit is set to 804).

**Comment by PeteRepeat77** [comment] 2016-02-07 21:56
This is repeated many times in my log. Only one that is repeated when limited playlist to X+1.

I created a playlist with a id equals rule and the playlist syncs the single track fine.

adding 1 tracks. first 5 are [
  {
    "id": "016abb53-7043-3f72-bf43-1a9205930e6b",
    "title": "Kik Yerself",
    "artist": "Radioactive Man",
    "album": "Booby Trap [UK]",
    "albumArtist": "Radioactive Man",
    "composer": "",
    "genre": "R&B",
    "durationMillis": 321538,
    "track": 5,
    "totalTracks": 0,
    "disc": 0,
    "totalDiscs": 0,
    "year": 2003,
    "playCount": 3,
    "rating": 5,
    "creationDate": 1429441209839729,
    "lastPlayed": 1432195023599308,
    "storeId": "Thctieskdkebd4kdtvdvpshpd74",
    "type": 6,
    "comment": "",
    "bitrate": 320
  }
]
Object {newTimestamp: null, upsertedTracks: Array[0], deletedIds: Array[0]}
done with diff upsert of 0
done with diff delete of 0
skipping forceUpdate since playlist is being updated: Thumbs Up (not heard in last month)
add response [
  [
    0,
    2,
    0
  ],
  [
    0,
    [
      [
        "016abb53-7043-3f72-bf43-1a9205930e6b",
        6,
        ""
      ]
    ]
  ]
]
not a 0-track add; retrying syncPlaylist [Array[3], Array[2]]
index for 03334274646832387952 0
syncPlaylist, attempt 4
lock Thumbs Up (not heard in last month)
Thumbs Up (not heard in last month) found 804
first is Object {id: "57930658-aa1f-3295-ae09-b0881e68bfe6", title: "Danger (The Bomb) (12` Mix)", artist: "Ministry of Sound (CD Series)", album: "Clubbers Guide To 2006, Cd 1:", albumArtist: ""â€¦}
playlist a1dcf89b-aebd-4607-8dd3-fed26e4628f6 has 803 entries.

**Comment by PeteRepeat77** [comment] 2016-02-07 22:21
That track is not in the original playlist having problems so seems to me like it's the culprit.

But a playlist with only the songs ID matching seems to work fine

**Comment by simon-weber** [comment] 2016-02-08 00:04
Nice job finding the track, but it's super weird that it works alone.

Here's an idea:
* navigate to that track in google music
* open the developer tools and navigate to the network tab
  * make sure it says "Recording network activity..."
* in google music, right click the track and add it to your autoplaylist
* go back to the network tab and find the "addtrackstoplaylist" request
* right click -> "copy response", then paste here
* right click -> "copy as curl", paste here, then remove everything but the "--data ..." bit

That'll tell us if Google is making the request differently from us.

I've also just pushed an update to automatically collect logging, which will hopefully give me more examples to cross-reference.

**Comment by PeteRepeat77** [comment] 2016-02-08 00:48
Think this is it. I'll try again to make sure I copied the right thing


[[0,2,0]
,[0,[["Thctieskdkebd4kdtvdvpshpd74",7,""]
]
]
]

**Comment by PeteRepeat77** [comment] 2016-02-08 00:52
Hmmm. It added to the playlist when it's done this way. I might try increasing the autoplaylist and see what happens now.

Should I go through all these steps again to make sure?

Just summarising the steps.

- Limit to 1 more than when playlist gets the problem.
- Save the log and find the "added 1 track" line that shol drepeat multiple times for the problematic track
- Creat a playlist with it's ID
- Use the develper tools and copy the response of the addtracktoplaylist after I add the problematic track.

**Comment by PeteRepeat77** [comment] 2016-02-08 00:54
It has now removed the song from the playlist once your extension refreshed which is expected I guess.

**Comment by simon-weber** [comment] 2016-02-08 01:00
The plot thickens. Was the most recent 0,2,0 response pulled from the developer tools opened on the same tab as Google Music? If so it does give us a lead - maybe Google expects type 6 tracks to be added as if they were type 7 tracks - but it's also weird that their own client would generate the same error.

To clarify: the instructions from https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/35#issuecomment-181144809 should all be done in the same tab as Google Music (not in the window with the extension logs). The steps you posted look correct for the earlier debugging idea, but I could still the output from `right click -> "copy as curl", paste here, then remove everything but the "--data ..." bit` in the Google Music network tab. That'll confirm if Google's client is doing something different from the extension.

Also, I just got my first sentry error report! It matches the data you're providing -- nice to see that it all hooked up properly!

**Comment by PeteRepeat77** [comment] 2016-02-08 01:00
curl "https://play.google.com/music/services/addtrackstoplaylist?u=0&format=jsarray&xt=CjUKATASMEFNLVdiWGdjOEJqSE52N1ZxQWsyN3hWSnpGMXRxX3hNaWc6MTQ1NDg5Mjc4NzEyOA"%"3D"%"3D&obfid=03334274646832387952" -H "origin: https://play.google.com" -H "accept-encoding: gzip, deflate" -H "accept-language: en-US,en;q=0.8" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36" -H "content-type: application/x-www-form-urlencoded;charset=UTF-8" -H "accept: */*" -H "referer: https://play.google.com/music/listen" -H "authority: play.google.com" -H "cookie: __utmt=1; __utma=45884901.1231204434.1450260048.1454880674.1454883032.82; __utmb=45884901.10.9.1454893071758; __utmc=45884901; __utmz=45884901.1450260048.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); sjsaid=ff19688e-92d1-441b-8f83-862b903d170a; xt=CjUKATASMEFNLVdiWGdjOEJqSE52N1ZxQWsyN3hWSnpGMXRxX3hNaWc6MTQ1NDg5Mjc4NzEyOA==; sjpref=v:100|; HSID=AYha_bB69K4_1gauG; SSID=AVTJCUodTJkxI0aR_; APISID=b26P3b8DaWBaSvMs/AtsQBupiQGoIhsDBu; SAPISID=wTg1pFnGQ3TmV5eg/AJ3Tyg4PTtrG88ohf; PLAY_ACTIVE_ACCOUNT=ICrt_XL61NBE_S0rhk8RpG0k65e0XwQVdDlvB6kxiQ8=peterbrown77.pb@gmail.com; PLAY_PREFS=CowECIGeuqaUHxKCBAoCQVUQxvGDoqAqGscDExQV8QGsAuEDwwSKBeMF5QXoBdcGjgiQlYEGkZWBBpKVgQaTlYEGlJWBBpeVgQaklYEGrZWBBreVgQa4lYEGwZWBBsSVgQbFlYEGyJWBBsmVgQbKlYEGzpWBBs-VgQbQlYEG1ZWBBtqVgQbdlYEG5pWBBueVgQbplYEG8ZWBBvuVgQaDloEGhZaBBoiWgQaMloEGjpaBBpGWgQaUloEGmZaBBp-WgQahloEGopaBBqSWgQanloEGypeBBu6XgQbvl4EGhZiBBqObgQatm4EGy5uBBrudgQa8nYEGw52BBsSdgQbFnYEGxp2BBsedgQbdnYEG552BBuydgQaQnoEGw5-BBuifgQb7n4EGpKCBBtqggQb1oIEGy6GBBsyhgQbNoYEG7qGBBvGhgQbiooEG6qKBBvOigQb3ooEGr6OBBvSjgQaOpIEGmqSBBp2kgQaepIEGsqSBBu-kgQavpYEG6aWBBv6lgQadpoEGxqaBBvemgQa3p4EGx6eBBs-ngQaiqIEGy6iBBsyogQbmqYEGvKyBBvusgQbBrYEG_q2BBoKugQajr4EGyK-BBtavgQbYr4EG4q-BBs-wgQaisYEGo7GBBuD8nDEoxvGDoqAqOiRlZmU3MTQyMC0zNzllLTRlM2QtYTFmYS03NzFmZjdiMWMxNmQ:S:ANO1ljIq05iJoYvTFw; _ga=GA1.3.888311326.1451770314; SID=DQAAAB0BAAAqEmTWMUjF0LMpuNC2GRaTVhczliwXAkM4wC20Ot7J-Ji0FeK_Ho1f5IuLPoW8VpLCERqVwwDO8zZhzhMdRXoRlIiVfivVRiqZkDcxTQxS0dBufetHuSRAYwfTxjTDAFYjNobutbC7-yBcmPGeEFtYJFypCXWs-WN6Mc4KQq8YpUBrZc8NK0386o7NIlftxbrQpALx7hFkQgDqA8GScP9gE8sVBjtV-tLTYO2L7-1jg9wx3zz2oKpW-GRdctC1Wbh09vCgLqVWbNGhvYk9TyBXiqx6jlFFDyzZE-ok-K9etAJk1EFMalNsbuX7rEyVvtoaRWCVjSAdGuy7FqHG15QfdQaXj6NLIyW9xF8xctw3TAjPfXwOCR5_5m0c9WjauGU; NID=76=KqCROx2B9M7-U0BpvMnPYMU8tAUdUVa22yeonStLd21Vx676API2SUQ8pvgKKC-yK9DJ-RK9uB5jTlbeW9LTTUcKd1-7qgoVtBweKc554VWin2bIBRGwrUw4u_QQtA06dlbKpAYqipf2-LdztW6dkH2A0QMM4cRIlOkElB0jjoT03_w4FZ3pm9Ajvphwxw-LaTbPgh4jQPOSSvI_gqqZ0ESJYOH1KDOGPWftJNJPte5FSwe04idK0mLqKw" -H "x-client-data: CKK2yQEIwbbJAQiAisoBCIqSygEI/ZXKAQ==" --data "[[""438lziywxcq3"",1],[""a1dcf89b-aebd-4607-8dd3-fed26e4628f6"",[[""Thctieskdkebd4kdtvdvpshpd74"",7]]]]" --compressed

**Comment by PeteRepeat77** [comment] 2016-02-08 01:01
Sorry I know it includes the data part but didn't want to delete any necessary bits.

Yes these two were copied from the play music tab

**Comment by simon-weber** [comment] 2016-02-08 01:02
No problem, I just edited it to include exactly what we need.

It looks like this confirms what I was thinking: type 6 tracks should be added as type 7 if they have a store id. That should be a quick change -- I'll push out an update shortly.

**Comment by PeteRepeat77** [comment] 2016-02-08 01:03
Great support!!!

**Comment by simon-weber** [comment] 2016-02-08 01:30
I just tried this with my AA test account and couldn't replicate what Google Music is doing :confused: 

Here's what I did:
* found example tracks of type 6
  * not all of them had a storeId
* for one with a store id:
  * add with library_id + 6: successful. This is what my extension is currently doing.
  * add with store_id + 6: not successful, though Google's server seemed to think it was and returned an entry id.
  * add with store_id + 7: successful, though it actually added a slightly different track (the store track was one second longer than my uploaded library track). This is what we noticed Google doing for you most recently. Strangely, Google marks the track of type 5 in the dom, which isn't a type I've ever seen before.

I also tested to see what Google client did when I added the track manually to a playlist. It always added with library_id + 6.

I'm going to play with this a bit more before making the change, since I don't understand what's going on yet.

**Comment by simon-weber** [comment] 2016-02-08 02:26
A few debugging questions for you, @PeteRepeat77:
* can you retry the steps from https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/35#issuecomment-181144809, but with a new, empty playlist? I'm curious if Google will use the type 6 request, or if it will use the type 7 request.
* from the track type, my expectation is that this track is one you uploaded, and that Google matched to a store track later on. Is that correct?
* can you try deleting and recreating the entire autoplaylist in the extension? It could be that the playlist is in a weird state (and the track is ok, as shown by the "id equals ..." autoplaylist working correctly).

**Comment by PeteRepeat77** [comment] 2016-02-08 10:45
I'll do all that when I'm in the office tomorrow.

**Comment by simon-weber** [comment] 2016-02-21 07:43
I'm hoping that change will improve this situation (more details in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/20#issuecomment-186769427). Let me know how it goes after you update.

**Comment by simon-weber** [comment] 2016-02-21 21:33
Here's an interesting finding: I noticed that an error response of yours had more tracks in the response than in the request. The response did contain all of the request ids, plus an extra 163 ids. Here they are: https://gist.github.com/simon-weber/eaec43468055c0d6ab57.

@PeteRepeat77 can you check if these are actual library ids? You should be able to tell with a "id equals ..." playlist.

**Comment by simon-weber** [comment] 2016-05-06 18:07
I'm going to close this since nobody has seen it for a while. Feel free to respond if it's still a problem and I'll reopen it.

**Comment by PeteRepeat77** [comment] 2016-05-06 22:21
Sorry for not updating. I recreated the play list a while back and believe the problem has gone now.

**Comment by simon-weber** [comment] 2016-05-07 01:21
No problem! Glad it's working for you.

**Comment by zigmachine** [comment] 2016-05-18 20:17
Hi,
I'm currently seeing this issue with a playlist.
The Autoplaylists test shows 22 tracks, but Google Music is only showing 20 tracks.
Not sure what the cause could be.

Autoplaylist info:
Synced 5/18/2016, 4:16:54 PM by Autoplaylists for Google Music™ to contain: genre contains "Soul" sort by playCount descending.

Thanks

**Comment by simon-weber** [comment] 2016-05-19 02:52
Hm. Do you notice anything different about the tracks that are missing? Maybe they're of a different type than the ones that are working (you can get the field in the test results by adding a sort on it)? Subscription tracks in general seem to cause more issues, so that's my guess right now.

If there's nothing noticeably different about them, try disabling and re-enabling the extension, then reloading the Google Music tab to see if that helps.

**Comment by simon-weber** [comment] 2016-08-21 22:32
There have a variety of improvements to sync quality recently, so I'm going to close this. Feel free to create a new issue if this happens again.

**Closed by simon-weber** 2016-08-21 22:32 UTC
Labels: bug
